sudo: required
dist: trusty
language: cpp

os:
  - linux

addons:
  apt:
    packages: ['libsnappy-dev', 'libprotobuf-dev', 'libgoogle-glog-dev']

compiler:
  - gcc

language: cpp

script:
  - git submodule init
  - git submodule update
  - cd ./binlog_sender && make && cd ..
  - cd ./nemo_to_blackwidow && make && cd ..
  - cd ./pika_port && make && cd ..
  - cd ./pika_to_txt && make && cd ..
  - cd ./txt_to_pika && make && cd ..
