sudo: required
dist: trusty
language: cpp

os:
  - linux

addons:
  apt:
    packages: ['libsnappy-dev', 'libprotobuf-dev', 'libgoogle-glog-dev']

compiler:
  - gcc  python

language: cpp python

script:
  - git submodule init
  - git submodule update
  - cd ./binlog_sender && make && cd ..
  - cd ./nemo_to_blackwidow && make && cd ..
  - cd ./pika_to_txt && make && cd ..
  - cd ./txt_to_pika && make && cd ..
  - cd ./pika-port/pika_port_2 && make && cd .. && cd ..
  - cd ./pika-port/pika_port_3 && make && cd .. && cd ..
  - cd ./manifest_generator && make && cd ..
  - cd ./ssdb_to_pika && make && cd ..
  - cd ./rdb_to_pika && ./install_rdb_tools.sh && make && cd ..
